# Generated by Django 5.0.1 on 2024-03-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='sesion_key',
            new_name='session_key',
        ),
    ]
